name: Jaehyeon Kim
avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Consultant at Cevo ğŸ‡¦ğŸ‡º â˜ AWS Community Builder ğŸ’­ Blogger ğŸš€ Data Streaming Enthusiast'
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
# location: Earth # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: dottami@gmail.com
  github: jaehyeon-kim
  linkedin: jaehyeon-kim-76b93429
  # twitter: 
  # patreon: 
  paypal: dottami
  rss: "" # Remove RSS
